# Generated by Django 5.0.3 on 2024-05-01 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('usuario', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('privacidad', models.CharField(choices=[('PUB', 'Público'), ('CON', 'Solo contactos')], default='PUB', max_length=4)),
                ('etiqueta', models.CharField(blank=True, choices=[('CONV', 'Convivencia'), ('ACAD', 'Académico'), ('AYUD', 'Ayuda/Orientación'), ('EMPL', 'Empleos')], max_length=5, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
