# Generated by Django 5.0.2 on 2024-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Red_Social_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
