# Generated by Django 5.0.3 on 2024-05-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Red_Social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_usuario',
            field=models.CharField(max_length=512),
        ),
    ]
