# Generated by Django 5.0.3 on 2024-04-23 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Red_Social_app', '0002_alter_post_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('CONV', 'Convivencia'), ('ACAD', 'Académico'), ('AYUD', 'Ayuda/Orientación'), ('EMPL', 'Empleos')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='privacidad',
            field=models.CharField(choices=[('PUB', 'Público'), ('CON', 'Solo contactos')], default='PUB', max_length=4),
        ),
    ]
