# Generated by Django 5.0.3 on 2024-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Red_Social_app', '0003_rename_imagen_post_imagen_post_etiqueta_post_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
